-- Supabase SQL schema for Kanchanpur Sporting Club
create table if not exists public.applications (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id),
  name text not null,
  father_name text,
  mother_name text,
  birth_year text,
  nid text,
  district text,
  thana text,
  village text,
  blood_group text,
  phone text,
  photo_url text,
  status text not null default 'pending',
  created_at timestamptz not null default now()
);

create table if not exists public.payments (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id),
  method text not null,
  amount numeric not null,
  transaction_id text not null,
  status text not null default 'pending',
  created_at timestamptz not null default now()
);

alter table public.applications enable row level security;
alter table public.payments enable row level security;

-- Users can submit/read their own records.
create policy "users insert applications"
on public.applications for insert to authenticated
with check (auth.uid() = user_id);

create policy "users read own applications"
on public.applications for select to authenticated
using (auth.uid() = user_id);

create policy "users insert payments"
on public.payments for insert to authenticated
with check (auth.uid() = user_id);

create policy "users read own payments"
on public.payments for select to authenticated
using (auth.uid() = user_id);

-- Admin policies should be added using a secure admin-role design.
-- Do NOT use a public policy that allows everyone to update applications/payments.
