
plugins {
    id "com.android.application"
    id "org.jetbrains.kotlin.android"
    id "com.google.gms.google-services"
}

android {
    namespace "com.kanchanpur.sportingclub"

    defaultConfig {
        applicationId "com.kanchanpur.sportingclub"
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName "1.0.0"
    }
}

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = "17"
    }
}

flutter {
    source "../.."
}

