
name: Build Flutter APK

on:
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '17'

      - name: Generate Firebase SHA fingerprints
        run: |
          mkdir -p ~/.android
          keytool -genkeypair -v \
            -keystore ~/.android/debug.keystore \
            -storepass android \
            -alias androiddebugkey \
            -keypass android \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -dname "CN=Android Debug,O=Android,C=US"

          echo "===== FIREBASE SHA FINGERPRINTS ====="

          keytool -list -v \
            -keystore ~/.android/debug.keystore \
            -storepass android \
            -alias androiddebugkey | grep -E "SHA1:|SHA256:"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.44.2'
          channel: stable
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Build release APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: kanchanpur-sporting-club-apk
          path: build/app/outputs/flutter-apk/app-release.apk

